#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import readline from 'readline';
import crypto from 'crypto';
import net from 'net';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const backendEnvPath = path.join(rootDir, 'backend', '.env');
const frontendEnvLocalPath = path.join(rootDir, 'frontend', '.env.local');

const args = new Set(process.argv.slice(2));
const autoYes = args.has('--yes');
const forceOverwrite = args.has('--force');
const noStart = args.has('--no-start');
const noInstall = args.has('--no-install');
const ensureOnly = args.has('--ensure');

function logStep(message) {
  console.log(`\n==> ${message}`);
}

function run(command, cwd = rootDir) {
  console.log(`$ ${command}`);
  execSync(command, { cwd, stdio: 'inherit' });
}

function checkNodeVersion() {
  const major = Number(process.versions.node.split('.')[0] || '0');
  if (major < 18) {
    throw new Error(`Node.js >= 18 is required, current: ${process.versions.node}`);
  }
}

function generateJwtSecret() {
  return crypto.randomBytes(24).toString('hex');
}

function readEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const env = {};
  const content = fs.readFileSync(filePath, 'utf8');

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const separatorIndex = line.indexOf('=');
    if (separatorIndex === -1) {
      continue;
    }

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    env[key] = value;
  }

  return env;
}

function buildConfig(existingEnv = {}) {
  return {
    port: existingEnv.PORT || '3001',
    frontendUrl: existingEnv.FRONTEND_URL || 'http://localhost:5173',
    nodeEnv: existingEnv.NODE_ENV || 'development',
    jwtSecret: existingEnv.JWT_SECRET || generateJwtSecret(),
    dashscopeApiKey: existingEnv.DASHSCOPE_API_KEY || '',
  };
}

function hasOwnEnvKey(env, key) {
  return Object.prototype.hasOwnProperty.call(env, key);
}

function writeFrontendEnv(config) {
  const content = [
    '# Auto-generated by scripts/setup-local.mjs',
    `VITE_BACKEND_URL=http://localhost:${config.port}`,
    '',
  ].join('\n');

  fs.writeFileSync(frontendEnvLocalPath, content, 'utf8');
}

function isPortAvailable(port) {
  const normalizedPort = Number(port);
  if (!Number.isInteger(normalizedPort) || normalizedPort <= 0) {
    return Promise.resolve(false);
  }

  return new Promise((resolve) => {
    const server = net.createServer();

    server.once('error', () => {
      resolve(false);
    });

    server.once('listening', () => {
      server.close(() => resolve(true));
    });

    server.listen(normalizedPort);
  });
}

async function findAvailablePort(startPort) {
  let candidate = Number(startPort) || 3001;

  while (!(await isPortAvailable(candidate))) {
    candidate += 1;
  }

  return String(candidate);
}

async function resolvePortConflict(config, prompt) {
  const portAvailable = await isPortAvailable(config.port);
  if (portAvailable) {
    return config;
  }

  const suggestedPort = await findAvailablePort(Number(config.port) + 1 || 3002);

  if (prompt) {
    const shouldUseSuggestedPort = await prompt.confirm(
      `Backend PORT ${config.port} is already in use. Switch to ${suggestedPort}?`,
      true,
    );

    if (!shouldUseSuggestedPort) {
      throw new Error(`PORT ${config.port} is already in use. Free that port or choose another one.`);
    }
  } else {
    console.log(`Port ${config.port} is already in use. Switching backend PORT to ${suggestedPort}.`);
  }

  return {
    ...config,
    port: suggestedPort,
  };
}

function createPrompt() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const ask = (question, defaultValue = '', required = false) =>
    new Promise((resolve) => {
      const suffix = defaultValue ? ` [${defaultValue}]` : '';
      rl.question(`${question}${suffix}: `, (input) => {
        const value = input.trim() || defaultValue;
        if (required && !value) {
          console.log('This value is required. Please try again.');
          resolve(ask(question, defaultValue, required));
          return;
        }
        resolve(value);
      });
    });

  const confirm = (question, defaultYes = true) =>
    new Promise((resolve) => {
      const hint = defaultYes ? ' [Y/n]' : ' [y/N]';
      rl.question(`${question}${hint}: `, (input) => {
        const v = input.trim().toLowerCase();
        if (!v) {
          resolve(defaultYes);
          return;
        }
        resolve(v === 'y' || v === 'yes');
      });
    });

  return {
    ask,
    confirm,
    close: () => rl.close(),
  };
}

function writeBackendEnv(config) {
  const content = [
    '# Auto-generated by scripts/setup-local.mjs',
    '# Local development defaults',
    `PORT=${config.port}`,
    `FRONTEND_URL=${config.frontendUrl}`,
    `NODE_ENV=${config.nodeEnv}`,
    '',
    '# Local JWT secret',
    `JWT_SECRET=${config.jwtSecret}`,
    '',
    '# Optional: enable AI endpoints',
    `DASHSCOPE_API_KEY=${config.dashscopeApiKey}`,
    '',
    '# Optional: mail settings (fill only if needed)',
    '# SMTP_HOST=',
    '# SMTP_PORT=',
    '# SMTP_USER=',
    '# SMTP_PASS=',
    '',
  ].join('\n');

  fs.writeFileSync(backendEnvPath, content, 'utf8');
}

async function main() {
  checkNodeVersion();

  const existingEnv = readEnvFile(backendEnvPath);
  let defaultConfig = buildConfig(existingEnv);
  const hasBackendEnv = fs.existsSync(backendEnvPath);
  const missingRequiredEnv = ['PORT', 'FRONTEND_URL', 'NODE_ENV', 'JWT_SECRET']
    .some((key) => !existingEnv[key]);
  const missingDashscopeEntry = !hasOwnEnvKey(existingEnv, 'DASHSCOPE_API_KEY');
  const portConflict = !(await isPortAvailable(defaultConfig.port));

  if (ensureOnly) {
    if (hasBackendEnv && !forceOverwrite && !missingRequiredEnv && !missingDashscopeEntry && !portConflict) {
      console.log('backend/.env is already configured.');
      return;
    }

    console.log('SpiritHub config check');
    console.log('Detected local backend config changes required. Launching guided setup.');

    let config = defaultConfig;

    if (!autoYes) {
      const prompt = createPrompt();
      try {
        config = {
          port: await prompt.ask('Backend PORT', defaultConfig.port, true),
          frontendUrl: await prompt.ask('FRONTEND_URL', defaultConfig.frontendUrl, true),
          nodeEnv: await prompt.ask('NODE_ENV', defaultConfig.nodeEnv, true),
          jwtSecret: await prompt.ask('JWT_SECRET', defaultConfig.jwtSecret, true),
          dashscopeApiKey: defaultConfig.dashscopeApiKey,
        };

        if (missingDashscopeEntry && !defaultConfig.dashscopeApiKey) {
          const shouldConfigureAi = await prompt.confirm('DASHSCOPE_API_KEY is not configured. Add it now?', false);
          if (shouldConfigureAi) {
            config.dashscopeApiKey = await prompt.ask('DASHSCOPE_API_KEY (optional)', '', false);
          }
        }

        config = await resolvePortConflict(config, prompt);
      } finally {
        prompt.close();
      }
    } else {
      config = await resolvePortConflict(config, null);
    }

    logStep('Writing backend/.env');
    writeBackendEnv(config);
    console.log(`Wrote ${path.relative(rootDir, backendEnvPath)}`);
    logStep('Writing frontend/.env.local');
    writeFrontendEnv(config);
    console.log(`Wrote ${path.relative(rootDir, frontendEnvLocalPath)}`);
    return;
  }

  console.log('SpiritHub local setup');
  console.log('This script will:');
  console.log('1) install frontend/backend dependencies');
  console.log('2) generate backend/.env with your local config');
  console.log('3) optionally start frontend + backend');

  let shouldWriteEnv = true;
  let shouldStart = !noStart;
  let config;

  if (autoYes) {
    shouldWriteEnv = !fs.existsSync(backendEnvPath) || forceOverwrite;
    config = {
      port: '3001',
      frontendUrl: 'http://localhost:5173',
      nodeEnv: 'development',
      jwtSecret: generateJwtSecret(),
      dashscopeApiKey: '',
    };
  } else {
    const prompt = createPrompt();
    try {
      if (fs.existsSync(backendEnvPath) && !forceOverwrite) {
        shouldWriteEnv = await prompt.confirm('backend/.env already exists. Overwrite it?', false);
      }

      config = {
        port: await prompt.ask('Backend PORT', '3001', true),
        frontendUrl: await prompt.ask('FRONTEND_URL', 'http://localhost:5173', true),
        nodeEnv: await prompt.ask('NODE_ENV', 'development', true),
        jwtSecret: await prompt.ask('JWT_SECRET', generateJwtSecret(), true),
        dashscopeApiKey: await prompt.ask('DASHSCOPE_API_KEY (optional)', '', false),
      };

      config = await resolvePortConflict(config, prompt);

      shouldStart = await prompt.confirm('Start frontend + backend after setup?', true);
    } finally {
      prompt.close();
    }
  }

  if (autoYes) {
    config = await resolvePortConflict(config, null);
  }

  if (!noInstall) {
    logStep('Installing dependencies');
    run('npm run install:all');
  }

  if (shouldWriteEnv) {
    logStep('Writing backend/.env');
    writeBackendEnv(config);
    console.log(`Wrote ${path.relative(rootDir, backendEnvPath)}`);
    logStep('Writing frontend/.env.local');
    writeFrontendEnv(config);
    console.log(`Wrote ${path.relative(rootDir, frontendEnvLocalPath)}`);
  } else {
    console.log('\n==> Keeping existing backend/.env');
  }

  if (shouldStart) {
    logStep('Starting frontend + backend');
    run('npm run dev');
    return;
  }

  console.log('\nSetup complete. Next step:');
  console.log('  npm run dev');
}

main().catch((err) => {
  console.error('\nSetup failed:');
  console.error(err.message || err);
  process.exit(1);
});
