#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import readline from 'readline';
import crypto from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const backendEnvPath = path.join(rootDir, 'backend', '.env');

const args = new Set(process.argv.slice(2));
const autoYes = args.has('--yes');
const forceOverwrite = args.has('--force');
const noStart = args.has('--no-start');

function logStep(message) {
  console.log(`\n==> ${message}`);
}

function run(command, cwd = rootDir) {
  console.log(`$ ${command}`);
  execSync(command, { cwd, stdio: 'inherit' });
}

function checkNodeVersion() {
  const major = Number(process.versions.node.split('.')[0] || '0');
  if (major < 18) {
    throw new Error(`Node.js >= 18 is required, current: ${process.versions.node}`);
  }
}

function generateJwtSecret() {
  return crypto.randomBytes(24).toString('hex');
}

function createPrompt() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const ask = (question, defaultValue = '', required = false) =>
    new Promise((resolve) => {
      const suffix = defaultValue ? ` [${defaultValue}]` : '';
      rl.question(`${question}${suffix}: `, (input) => {
        const value = input.trim() || defaultValue;
        if (required && !value) {
          console.log('This value is required. Please try again.');
          resolve(ask(question, defaultValue, required));
          return;
        }
        resolve(value);
      });
    });

  const confirm = (question, defaultYes = true) =>
    new Promise((resolve) => {
      const hint = defaultYes ? ' [Y/n]' : ' [y/N]';
      rl.question(`${question}${hint}: `, (input) => {
        const v = input.trim().toLowerCase();
        if (!v) {
          resolve(defaultYes);
          return;
        }
        resolve(v === 'y' || v === 'yes');
      });
    });

  return {
    ask,
    confirm,
    close: () => rl.close(),
  };
}

function writeBackendEnv(config) {
  const content = [
    '# Auto-generated by scripts/setup-local.mjs',
    '# Local development defaults',
    `PORT=${config.port}`,
    `FRONTEND_URL=${config.frontendUrl}`,
    `NODE_ENV=${config.nodeEnv}`,
    '',
    '# Local JWT secret',
    `JWT_SECRET=${config.jwtSecret}`,
    '',
    '# Optional: enable AI endpoints',
    `DASHSCOPE_API_KEY=${config.dashscopeApiKey}`,
    '',
    '# Optional: mail settings (fill only if needed)',
    '# SMTP_HOST=',
    '# SMTP_PORT=',
    '# SMTP_USER=',
    '# SMTP_PASS=',
    '',
  ].join('\n');

  fs.writeFileSync(backendEnvPath, content, 'utf8');
}

async function main() {
  checkNodeVersion();

  console.log('SpiritHub local setup');
  console.log('This script will:');
  console.log('1) install frontend/backend dependencies');
  console.log('2) generate backend/.env with your local config');
  console.log('3) optionally start frontend + backend');

  let shouldWriteEnv = true;
  let shouldStart = !noStart;
  let config;

  if (autoYes) {
    shouldWriteEnv = !fs.existsSync(backendEnvPath) || forceOverwrite;
    config = {
      port: '3001',
      frontendUrl: 'http://localhost:5173',
      nodeEnv: 'development',
      jwtSecret: generateJwtSecret(),
      dashscopeApiKey: '',
    };
  } else {
    const prompt = createPrompt();
    try {
      if (fs.existsSync(backendEnvPath) && !forceOverwrite) {
        shouldWriteEnv = await prompt.confirm('backend/.env already exists. Overwrite it?', false);
      }

      config = {
        port: await prompt.ask('Backend PORT', '3001', true),
        frontendUrl: await prompt.ask('FRONTEND_URL', 'http://localhost:5173', true),
        nodeEnv: await prompt.ask('NODE_ENV', 'development', true),
        jwtSecret: await prompt.ask('JWT_SECRET', generateJwtSecret(), true),
        dashscopeApiKey: await prompt.ask('DASHSCOPE_API_KEY (optional)', '', false),
      };

      shouldStart = await prompt.confirm('Start frontend + backend after setup?', true);
    } finally {
      prompt.close();
    }
  }

  logStep('Installing dependencies');
  run('npm run install:all');

  if (shouldWriteEnv) {
    logStep('Writing backend/.env');
    writeBackendEnv(config);
    console.log(`Wrote ${path.relative(rootDir, backendEnvPath)}`);
  } else {
    console.log('\n==> Keeping existing backend/.env');
  }

  if (shouldStart) {
    logStep('Starting frontend + backend');
    run('npm run dev');
    return;
  }

  console.log('\nSetup complete. Next step:');
  console.log('  npm run dev');
}

main().catch((err) => {
  console.error('\nSetup failed:');
  console.error(err.message || err);
  process.exit(1);
});
